[package]
name = "stm32f401-test"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2"
nb = "1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"   # https://crates.io/keywords/panic-impl

[dependencies.stm32f4xx-hal]
version = "0.14.0"
features = ["stm32f401", "rt"]

[profile.release]
opt-level = 'z' # turn on maximum optimizations. We only have 64kB
lto = true      # Link-time-optimizations for further size reduction
