[package]
name = "stm32g030-test"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2"
nb = "1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"   # https://crates.io/keywords/panic-impl

[dependencies.stm32g0xx-hal]
version = "0.2.0"
features = ["stm32g030", "rt"]

[profile.release]
opt-level = 'z' # turn on maximum optimizations. We only have 64kB
lto = true      # Link-time-optimizations for further size reduction
